name: WaniKani Notifier Heartbeat 🦀

on:
  schedule:
    # - cron: '0 5 * * 1'  # Every Monday at 06:00 or 7:00 CET
  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./heartbeat.sh

      - name: Run heartbeat
        run: ./heartbeat.sh
        env:
          GMAIL_CLIENT_ID:     ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          MY_EMAIL:            ${{ secrets.MY_EMAIL }}
          FROM_EMAIL:          ${{ secrets.FROM_EMAIL }}
